In [1]:
import numpy as np # should always be like this when using numpy!!!

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

How many negative numbers are there?

In [3]:
np.negative(a) 
(a < 0).sum()
# 4

4

How many positive numbers are there?

In [4]:
np.positive(a) 
(a > 0).sum()
#5

5

How many even positive numbers are there?

#3

If you were to add 3 to each data point, 
how many positive numbers would there be?

In [5]:
((a + 3) > 0).sum()
#10

10

If you squared each number, 
what would the new mean and standard deviation be?

In [6]:
a_squared = a ** 2
a_squared


array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [7]:
a_squared.mean()


74.0

In [61]:
a_squared.std()


144.0243035046516

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [62]:
a_centered = a - (a.mean())
a_centered


array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [63]:
a_centered.mean()

0.0

Calculate the z-score for each data point. Recall that the z-score is given by:

In [28]:
(a -mean) / std

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

part 1

In [14]:
s = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [15]:
# sum_of_s = np.sum(s)
# sum_of_s
sum(s)

55

In [16]:
# min_of_s = np.min(s)
# min_of_s
min(s)

1

In [17]:
# max_of_s = np.max(s)
# max_of_s
max(s)


10

In [65]:
# mean_of_s = np.mean(s)
# mean_of_s 
sum(s)/ len(s)

5.5

In [68]:
# product_of_s = np.prod(s)
# product_of_s
product_of_s = 1

for i in s:
    product_of_s *= i
    
product_of_s

3628800

In [69]:
# squares_of_s = np.square(s)
# squares_of_s

squares_of_s= []

for i in s:
#     print(i**2)
    squares_of_s.append(i**2)

squares_of_s

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [45]:
# odds_in_s = (s[s % 2 != 0])
# odds_in_s

odds_in_a = []

for i in a:
    if i % 2 == 1:
#         print(i)
        odds_in_a.append(i)
        
odds_in_s

array([1, 3, 5, 7, 9])

In [47]:
evens_in_s = (s[s % 2 == 0])
evens_in_s

array([ 2,  4,  6,  8, 10])

part 2 

In [17]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b

[[3, 4, 5], [6, 7, 8]]

In [36]:
b = np.array(b)

In [37]:
np.sum(b)
#finding the sum of all of it 

33

In [38]:
np.min(b)
#finding the min

3

In [39]:
 np.max(b)
#finding the max

8

In [40]:
np.mean(b)  
#finding the mean 

5.5

In [41]:
np.prod(b)


20160

In [42]:
np.square(b)       #finding the sqaure of all



array([[ 9, 16, 25],
       [36, 49, 64]])

In [43]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [44]:
b [b % 2 == 1]

array([3, 5, 7])

In [45]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)


In [46]:
b [b % 2 == 0]

array([4, 6, 8])

In [47]:
ba = np.array(b)
ba.shape

(2, 3)

In [48]:
t = np.transpose(b)
t

array([[3, 6],
       [4, 7],
       [5, 8]])

In [49]:
bs = b.reshape(1,6)
bs

array([[3, 4, 5, 6, 7, 8]])

In [50]:
bd = b.reshape(6,1)
bd

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

part 3

In [51]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [44]:
np.prod(c)

362880

In [45]:
np.max(c)

9

In [46]:
np.min(c)

1

In [47]:
np.sum(c)

45

In [48]:
std = np.std(c)
std

2.581988897471611

In [49]:
np.var(c)

6.666666666666667

In [50]:
ca = np.array(c)
ca.shape

(3, 3)

In [51]:
cp = np.transpose(c)
cp

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
res = np.dot(c, cp)
res

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [53]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [154]:
sin = np.sin(d)
sin

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [155]:
cos = np.cos(d)
cos

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [156]:
tan = np.tan(d)
tan

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [56]:
# neg = np.negative(d)
# neg
d (d < 0)

TypeError: '<' not supported between instances of 'list' and 'int'

In [160]:
pos = np.positive(d)
pos

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [162]:
un = np.unique(d)
un

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [ ]:
# 11

In [164]:
da = np.array(d)
da.shape

(3, 6)

In [174]:
m = np.transpose(d)
m

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [173]:
nd = m.reshape(9,2)
nd

array([[ 90,  45],
       [ 60,  30],
       [-90,  45],
       [ 45, -30],
       [-45,   0],
       [270,  90],
       [120,  90],
       [-45, 180],
       [  0, 180]])